# SwiftLint config: VibeTunnel
# Base rules: Peekaboo defaults (../Peekaboo/.swiftlint.yml + ../Peekaboo/.swiftlint-ci.yml), adapted to VibeTunnel paths.

included:
  - ../mac/VibeTunnel
  - ../ios/VibeTunnel

excluded:
  - ../mac/VibeTunnelTests
  - ../mac/VibeTunnelUITests
  - ../ios/VibeTunnelTests
  - ../mac/build
  - ../ios/build
  - ../mac/.build
  - ../ios/.build
  - Carthage
  - Pods
  - DerivedData
  - .build
  - .swiftpm
  - "**/Generated"
  - "**/Resources"
  - "**/.swiftpm"
  - "**/DerivedData"
  - "**/Package.swift"
  - "*.playground"
  - Package.swift
  - "*.xcodeproj"

analyzer_rules:
  - unused_declaration
  - unused_import

opt_in_rules:
  - array_init
  - closure_spacing
  - contains_over_first_not_nil
  - empty_count
  - empty_string
  - explicit_init
  - fallthrough
  - fatal_error_message
  - first_where
  - joined_default_parameter
  - last_where
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - sorted_first_last
  - switch_case_alignment
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

disabled_rules:
  # Swift 6 requires explicit self - disable explicit_self rule
  - explicit_self

  # SwiftFormat handles these
  - trailing_whitespace
  - trailing_newline
  - trailing_comma
  - vertical_whitespace
  - indentation_width

  # Too restrictive or not applicable
  - identifier_name
  - file_header
  - explicit_top_level_acl
  - explicit_acl
  - explicit_type_interface
  - missing_docs
  - required_deinit
  - prefer_nimble
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - anonymous_argument_in_multiline_closure
  - no_extension_access_modifier
  - no_grouping_extension
  - switch_case_on_newline
  - strict_fileprivate
  - extension_access_modifier
  - convenience_type
  - no_magic_numbers
  - one_declaration_per_file
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - superfluous_else
  - number_separator
  - prefixed_toplevel_constant
  - opening_brace
  - trailing_closure
  - contrasted_opening_brace
  - sorted_imports
  - redundant_type_annotation
  - shorthand_optional_binding
  - untyped_error_in_catch
  - file_name
  - todo

  # CI defaults: keep warnings low
  - line_length
  - function_body_length
  - cyclomatic_complexity
  - file_length
  - type_body_length
  - function_parameter_count
  - nesting
  - multiple_closures_with_trailing_closure
  - void_return
  - force_cast
  - force_try
  - for_where
  - superfluous_disable_command
