/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Activity {
  timestamp: number
  status: string
  details?: string
}
export declare function initPtySystem(): void
export declare class NativePty {
  constructor(shell?: string | undefined | null, args?: Array<string> | undefined | null, env?: Record<string, string> | undefined | null, cwd?: string | undefined | null, cols?: number | undefined | null, rows?: number | undefined | null)
  write(data: Buffer): void
  resize(cols: number, rows: number): void
  getPid(): number
  kill(signal?: string | undefined | null): void
  readOutput(timeoutMs?: number | undefined | null): Buffer | null
  checkExitStatus(): number | null
  setOnData(callback: (data: Buffer) => void): void
  destroy(): void
}
export declare class ActivityDetector {
  constructor()
  detect(data: Buffer): Activity | null
}
